export const emergencySymptoms = [
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Shortness of breath",
      "extras": {},
      "id": "s_2",
      "image_source": null,
      "image_url": null,
      "name": "Shortness of breath",
      "parent_id": null,
      "parent_relation": null,
      "question": "Shortness of breath",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Unconsciousness",
      "extras": {},
      "id": "s_10",
      "image_source": null,
      "image_url": null,
      "name": "Unconsciousness",
      "parent_id": null,
      "parent_relation": null,
      "question": "Is the person unconscious?",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Symptoms quickly worsening",
      "extras": {},
      "id": "s_12",
      "image_source": null,
      "image_url": null,
      "name": "Symptoms quickly worsening",
      "parent_id": null,
      "parent_relation": null,
      "question": "Are your symptoms rapidly worsening?",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Rapid breathing",
      "extras": {},
      "id": "s_13",
      "image_source": null,
      "image_url": null,
      "name": "Rapid breathing",
      "parent_id": null,
      "parent_relation": null,
      "question": "Are you breathing very fast?",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Coughing up blood",
      "extras": {},
      "id": "s_14",
      "image_source": null,
      "image_url": null,
      "name": "Coughing up blood",
      "parent_id": null,
      "parent_relation": null,
      "question": "Are you coughing up blood?",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Not responding normally",
      "extras": {},
      "id": "s_11",
      "image_source": null,
      "image_url": null,
      "name": "Not responding normally",
      "parent_id": null,
      "parent_relation": null,
      "question": "Is the person responding normally?",
      "seriousness": "emergency",
      "sex_filter": "both"
  }
]