export const nonSeriousRisks = [
    {
        "category": "Risk factors",
        "common_name": "No significant contact with an infected person",
        "extras": {},
        "id": "p_11",
        "image_source": null,
        "image_url": null,
        "name": "No significant contact with an infected person",
        "question": "Other type of contact",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "No contact with an infected person",
        "extras": {},
        "id": "p_15",
        "image_source": null,
        "image_url": null,
        "name": "No contact with an infected person",
        "question": "None of the above",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Current cancer",
        "extras": {},
        "id": "p_18",
        "image_source": null,
        "image_url": null,
        "name": "Current cancer",
        "question": "Current cancer",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Diseases or drugs that weaken immune system",
        "extras": {},
        "id": "p_19",
        "image_source": null,
        "image_url": null,
        "name": "Diseases or drugs that weaken immune system",
        "question": "Diseases or drugs that weaken immune system",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Obesity",
        "extras": {},
        "id": "p_24",
        "image_source": null,
        "image_url": null,
        "name": "Obesity",
        "question": "Obesity",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Long-term stay at a care facility or nursing home",
        "extras": {},
        "id": "p_22",
        "image_source": null,
        "image_url": null,
        "name": "Long-term stay at a care facility or nursing home",
        "question": "Long-term stay at a care facility or nursing home",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Diabetes",
        "extras": {},
        "id": "p_23",
        "image_source": null,
        "image_url": null,
        "name": "Diabetes",
        "question": "Diabetes",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Cardiovascular disease",
        "extras": {},
        "id": "p_17",
        "image_source": null,
        "image_url": null,
        "name": "Cardiovascular disease",
        "question": "Cardiovascular disease",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "History of chronic lung disease",
        "extras": {},
        "id": "p_16",
        "image_source": null,
        "image_url": null,
        "name": "History of chronic lung disease",
        "question": "History of chronic lung disease",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "History of chronic liver disease",
        "extras": {},
        "id": "p_20",
        "image_source": null,
        "image_url": null,
        "name": "History of chronic liver disease",
        "question": "History of chronic liver disease",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "History of chronic kidney disease",
        "extras": {},
        "id": "p_21",
        "image_source": null,
        "image_url": null,
        "name": "History of chronic kidney disease",
        "question": "History of chronic kidney disease",
        "seriousness": "normal",
        "sex_filter": "both"
    }
]