export const riskFactors = [
    {
        "category": "Risk factors",
        "common_name": "Community transmission country",
        "extras": {},
        "id": "p_5",
        "image_source": null,
        "image_url": null,
        "name": "Community transmission country",
        "question": "In the past 14 days have you traveled to or resided in a country with many local cases of COVID-19?",
        "seriousness": "serious",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Caring for COVID-19 suspected person without protection",
        "extras": {},
        "id": "p_25",
        "image_source": null,
        "image_url": null,
        "name": "Caring for COVID-19 suspected person without protection",
        "question": "I have provided direct care to such a person, without the use of a protective mask and gloves",
        "seriousness": "serious",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Direct physical contact with a person suspected of having COVID-19",
        "extras": {},
        "id": "p_26",
        "image_source": null,
        "image_url": null,
        "name": "Direct physical contact with a person suspected of having COVID-19",
        "question": "I had direct physical contact with such a person",
        "seriousness": "serious",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Prolonged direct contact with a person suspected of having COVID-19",
        "extras": {},
        "id": "p_27",
        "image_source": null,
        "image_url": null,
        "name": "Prolonged direct contact with a person suspected of having COVID-19",
        "question": "I had face-to-face contact with such a person within 1 meter (3 feet) for longer than 15 minutes",
        "seriousness": "serious",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "No significant contact with an infected person",
        "extras": {},
        "id": "p_11",
        "image_source": null,
        "image_url": null,
        "name": "No significant contact with an infected person",
        "question": "Other type of contact",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "No contact with an infected person",
        "extras": {},
        "id": "p_15",
        "image_source": null,
        "image_url": null,
        "name": "No contact with an infected person",
        "question": "None of the above",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Current cancer",
        "extras": {},
        "id": "p_18",
        "image_source": null,
        "image_url": null,
        "name": "Current cancer",
        "question": "Current cancer",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Diseases or drugs that weaken immune system",
        "extras": {},
        "id": "p_19",
        "image_source": null,
        "image_url": null,
        "name": "Diseases or drugs that weaken immune system",
        "question": "Diseases or drugs that weaken immune system",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Obesity",
        "extras": {},
        "id": "p_24",
        "image_source": null,
        "image_url": null,
        "name": "Obesity",
        "question": "Obesity",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Long-term stay at a care facility or nursing home",
        "extras": {},
        "id": "p_22",
        "image_source": null,
        "image_url": null,
        "name": "Long-term stay at a care facility or nursing home",
        "question": "Long-term stay at a care facility or nursing home",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Diabetes",
        "extras": {},
        "id": "p_23",
        "image_source": null,
        "image_url": null,
        "name": "Diabetes",
        "question": "Diabetes",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "Cardiovascular disease",
        "extras": {},
        "id": "p_17",
        "image_source": null,
        "image_url": null,
        "name": "Cardiovascular disease",
        "question": "Cardiovascular disease",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "History of chronic lung disease",
        "extras": {},
        "id": "p_16",
        "image_source": null,
        "image_url": null,
        "name": "History of chronic lung disease",
        "question": "History of chronic lung disease",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "History of chronic liver disease",
        "extras": {},
        "id": "p_20",
        "image_source": null,
        "image_url": null,
        "name": "History of chronic liver disease",
        "question": "History of chronic liver disease",
        "seriousness": "normal",
        "sex_filter": "both"
    },
    {
        "category": "Risk factors",
        "common_name": "History of chronic kidney disease",
        "extras": {},
        "id": "p_21",
        "image_source": null,
        "image_url": null,
        "name": "History of chronic kidney disease",
        "question": "History of chronic kidney disease",
        "seriousness": "normal",
        "sex_filter": "both"
    }
]