export const riskFactors = [
  {
      "category": "Risk factors",
      "common_name": "Community transmission country",
      "extras": {},
      "id": "p_5",
      "image_source": null,
      "image_url": null,
      "name": "Community transmission country",
      "question": "In the past 14 days have you traveled to or resided in a country with many local cases of COVID-19?",
      "seriousness": "serious",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "No significant contact with an infected person",
      "extras": {},
      "id": "p_11",
      "image_source": null,
      "image_url": null,
      "name": "No significant contact with an infected person",
      "question": "Other type of contact",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "No contact with an infected person",
      "extras": {},
      "id": "p_15",
      "image_source": null,
      "image_url": null,
      "name": "No contact with an infected person",
      "question": "None of the above",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "Living or caring for COVID-19 suspected person",
      "extras": {},
      "id": "p_12",
      "image_source": null,
      "image_url": null,
      "name": "Living or caring for COVID-19 suspected person",
      "question": "I live with or have provided care to, without the use of a protective mask or gloves, a person suspected of having COVID-19",
      "seriousness": "serious",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "Traveling or staying with COVID-19 suspected person",
      "extras": {},
      "id": "p_13",
      "image_source": null,
      "image_url": null,
      "name": "Traveling or staying with COVID-19 suspected person",
      "question": "I have shared the same closed environment (e.g., classroom, workspace, gym) with or traveled in close proximity (1 m or 3 feet) to a person suspected of having COVID-19.",
      "seriousness": "serious",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "Prolonged direct contact with a person suspected of having COVID-19",
      "extras": {},
      "id": "p_14",
      "image_source": null,
      "image_url": null,
      "name": "Prolonged direct contact with a person suspected of having COVID-19",
      "question": "I had face-to-face contact within 1 meter (3 feet) for longer than 15 minutes with a person suspected of having COVID-19",
      "seriousness": "serious",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "History of chronic lung disease",
      "extras": {},
      "id": "p_16",
      "image_source": null,
      "image_url": null,
      "name": "History of chronic lung disease",
      "question": "History of chronic lung disease",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "History of heart failure",
      "extras": {},
      "id": "p_17",
      "image_source": null,
      "image_url": null,
      "name": "History of heart failure",
      "question": "History of heart failure",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "Current cancer",
      "extras": {},
      "id": "p_18",
      "image_source": null,
      "image_url": null,
      "name": "Current cancer",
      "question": "Current cancer",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "Diseases or drugs that weaken immune system",
      "extras": {},
      "id": "p_19",
      "image_source": null,
      "image_url": null,
      "name": "Diseases or drugs that weaken immune system",
      "question": "Diseases or drugs that weaken immune system",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "History of chronic liver disease",
      "extras": {},
      "id": "p_20",
      "image_source": null,
      "image_url": null,
      "name": "History of chronic liver disease",
      "question": "History of chronic liver disease",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "History of chronic kidney disease",
      "extras": {},
      "id": "p_21",
      "image_source": null,
      "image_url": null,
      "name": "History of chronic kidney disease",
      "question": "History of chronic kidney disease",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Risk factors",
      "common_name": "Long-term stay at a care facility or nursing home",
      "extras": {},
      "id": "p_22",
      "image_source": null,
      "image_url": null,
      "name": "Long-term stay at a care facility or nursing home",
      "question": "Long-term stay at a care facility or nursing home",
      "seriousness": "normal",
      "sex_filter": "both"
  }
]