export const symptoms = [
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Fever",
      "extras": {},
      "id": "s_0",
      "image_source": null,
      "image_url": null,
      "name": "Fever",
      "parent_id": null,
      "parent_relation": null,
      "question": "Fever",
      "seriousness": "serious",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Cough",
      "extras": {},
      "id": "s_1",
      "image_source": null,
      "image_url": null,
      "name": "Cough",
      "parent_id": null,
      "parent_relation": null,
      "question": "Cough",
      "seriousness": "serious",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Shortness of breath",
      "extras": {},
      "id": "s_2",
      "image_source": null,
      "image_url": null,
      "name": "Shortness of breath",
      "parent_id": null,
      "parent_relation": null,
      "question": "Shortness of breath",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Unconsciousness",
      "extras": {},
      "id": "s_10",
      "image_source": null,
      "image_url": null,
      "name": "Unconsciousness",
      "parent_id": null,
      "parent_relation": null,
      "question": "Is the person unconscious?",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Not responding normally",
      "extras": {},
      "id": "s_11",
      "image_source": null,
      "image_url": null,
      "name": "Not responding normally",
      "parent_id": null,
      "parent_relation": null,
      "question": "Is the person responding normally?",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Symptoms quickly worsening",
      "extras": {},
      "id": "s_12",
      "image_source": null,
      "image_url": null,
      "name": "Symptoms quickly worsening",
      "parent_id": null,
      "parent_relation": null,
      "question": "Are your symptoms rapidly worsening?",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Fever between 37.5°C and 38°C (99.5°F and 100.4°F)",
      "extras": {},
      "id": "s_22",
      "image_source": null,
      "image_url": null,
      "name": "Fever between 37.5°C and 38°C (99.5°F and 100.4°F)",
      "parent_id": null,
      "parent_relation": null,
      "question": "Between 37.5°C and 38°C (99.5°F and 100.4°F)",
      "seriousness": "serious",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Fever between 38°C and 40°C (100.4°F and 104°F)",
      "extras": {},
      "id": "s_23",
      "image_source": null,
      "image_url": null,
      "name": "Fever between 38°C and 40°C (100.4°F and 104°F)",
      "parent_id": null,
      "parent_relation": null,
      "question": "Between 38°C and 40°C (100.4°F and 104°F)",
      "seriousness": "serious",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Fever over 40°C (104°F)",
      "extras": {},
      "id": "s_4",
      "image_source": null,
      "image_url": null,
      "name": "Fever over 40°C (104°F)",
      "parent_id": null,
      "parent_relation": null,
      "question": "Over 40°C (104°F)",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Fever not measured",
      "extras": {},
      "id": "s_5",
      "image_source": null,
      "image_url": null,
      "name": "Fever not measured",
      "parent_id": null,
      "parent_relation": null,
      "question": "I haven’t taken my temperature",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Rapid breathing",
      "extras": {},
      "id": "s_13",
      "image_source": null,
      "image_url": null,
      "name": "Rapid breathing",
      "parent_id": null,
      "parent_relation": null,
      "question": "Are you breathing very fast?",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Coughing up blood",
      "extras": {},
      "id": "s_14",
      "image_source": null,
      "image_url": null,
      "name": "Coughing up blood",
      "parent_id": null,
      "parent_relation": null,
      "question": "Are you coughing up blood?",
      "seriousness": "emergency",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Fatigue",
      "extras": {},
      "id": "s_15",
      "image_source": null,
      "image_url": null,
      "name": "Fatigue",
      "parent_id": null,
      "parent_relation": null,
      "question": "Fatigue",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Muscle pain",
      "extras": {},
      "id": "s_16",
      "image_source": null,
      "image_url": null,
      "name": "Muscle pain",
      "parent_id": null,
      "parent_relation": null,
      "question": "Muscle pain",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Chills",
      "extras": {},
      "id": "s_17",
      "image_source": null,
      "image_url": null,
      "name": "Chills",
      "parent_id": null,
      "parent_relation": null,
      "question": "Chills",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Headache",
      "extras": {},
      "id": "s_18",
      "image_source": null,
      "image_url": null,
      "name": "Headache",
      "parent_id": null,
      "parent_relation": null,
      "question": "Headache",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Diarrhea",
      "extras": {},
      "id": "s_19",
      "image_source": null,
      "image_url": null,
      "name": "Diarrhea",
      "parent_id": null,
      "parent_relation": null,
      "question": "Diarrhea",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Nausea",
      "extras": {},
      "id": "s_20",
      "image_source": null,
      "image_url": null,
      "name": "Nausea",
      "parent_id": null,
      "parent_relation": null,
      "question": "Nausea",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Sore throat",
      "extras": {},
      "id": "s_21",
      "image_source": null,
      "image_url": null,
      "name": "Sore throat",
      "parent_id": null,
      "parent_relation": null,
      "question": "Sore throat",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "common_name": "Impaired taste or smell",
      "extras": {},
      "id": "s_24",
      "image_source": null,
      "image_url": null,
      "name": "Impaired taste or smell",
      "parent_id": null,
      "parent_relation": null,
      "question": "Impaired taste or smell",
      "seriousness": "normal",
      "sex_filter": "both"
  }
]