export const symptomsNonEmergency = [
  {
      "category": "Signs and symptoms",
      "children": [],
      "extras": {},
      "id": "s_1",
      "image_source": null,
      "image_url": null,
      "name": "Cough",
      "parent_id": null,
      "parent_relation": null,
      "question": "Cough",
      "seriousness": "serious",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "extras": {},
      "id": "s_15",
      "image_source": null,
      "image_url": null,
      "name": "Fatigue",
      "parent_id": null,
      "parent_relation": null,
      "question": "Fatigue",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "extras": {},
      "id": "s_16",
      "image_source": null,
      "image_url": null,
      "name": "Muscle pain",
      "parent_id": null,
      "parent_relation": null,
      "question": "Muscle pain",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "extras": {},
      "id": "s_17",
      "image_source": null,
      "image_url": null,
      "name": "Chills",
      "parent_id": null,
      "parent_relation": null,
      "question": "Chills",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "extras": {},
      "id": "s_18",
      "image_source": null,
      "image_url": null,
      "name": "Headache",
      "parent_id": null,
      "parent_relation": null,
      "question": "Headache",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "extras": {},
      "id": "s_19",
      "image_source": null,
      "image_url": null,
      "name": "Diarrhea",
      "parent_id": null,
      "parent_relation": null,
      "question": "Diarrhea",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "extras": {},
      "id": "s_20",
      "image_source": null,
      "image_url": null,
      "name": "Nausea",
      "parent_id": null,
      "parent_relation": null,
      "question": "Nausea",
      "seriousness": "normal",
      "sex_filter": "both"
  },
  {
      "category": "Signs and symptoms",
      "children": [],
      "extras": {},
      "id": "s_21",
      "image_source": null,
      "image_url": null,
      "name": "Sore throat",
      "parent_id": null,
      "parent_relation": null,
      "question": "Sore throat",
      "seriousness": "normal",
      "sex_filter": "both"
  },
    {
        "category": "Signs and symptoms",
        "children": [],
        "extras": {},
        "id": "s_24",
        "image_source": null,
        "image_url": null,
        "name": "Impaired taste or smell",
        "parent_id": null,
        "parent_relation": null,
        "question": "Impaired taste or smell",
        "seriousness": "normal",
        "sex_filter": "both"
    }
]